export default {
	'block-no-empty': true,
	'color-no-invalid-hex': true,
	'comment-no-empty': true,
	'declaration-block-no-duplicate-properties': [ true, { ignore: [ 'consecutive-duplicates-with-different-values' ] } ],
	'declaration-block-no-shorthand-property-overrides': true,
	'font-family-no-duplicate-names': true,
	'font-family-no-missing-generic-family-keyword': true,
	'function-calc-no-unspaced-operator': true,
	'function-linear-gradient-no-nonstandard-direction': true,
	'keyframe-declaration-no-important': true,
	'media-feature-name-no-unknown': true,
	'no-duplicate-at-import-rules': true,
	'no-duplicate-selectors': true,
	'no-empty-source': true,
	'no-invalid-double-slash-comments': true,
	'property-no-unknown': true,
	'selector-pseudo-class-no-unknown': true,
	'selector-pseudo-element-no-unknown': true,
	'selector-type-no-unknown': true,
	'string-no-newline': true,
	'unit-no-unknown': true,
	'number-max-precision': 3,
	'declaration-block-single-line-max-declarations': 1,
	'selector-max-universal': 2,
	'no-unknown-animations': true,
	'font-family-name-quotes': 'always-where-recommended',
	'length-zero-no-unit': true,
	'value-keyword-case': [
		'lower',
		{
			camelCaseSvgKeywords: true,
		},
	],
	'selector-attribute-quotes': 'always',
	'selector-type-case': 'lower',
	'comment-whitespace-inside': 'always',
};
