export default {
	// Possible problems
	// These rules relate to possible logic errors in code:
	'array-callback-return': [ 'error', { allowImplicit: true } ],
	'constructor-super': 'error',
	'for-direction': 'error',
	'getter-return': 'error',
	'no-async-promise-executor': 'error',
	'no-await-in-loop': 'off',
	'no-class-assign': 'error',
	'no-compare-neg-zero': 'error',
	'no-cond-assign': 'error',
	'no-const-assign': 'error',
	'no-constant-binary-expression': 'error',
	'no-constant-condition': 'error',
	'no-constructor-return': 'error',
	'no-control-regex': 'error',
	'no-debugger': 'error',
	'no-dupe-args': 'error',
	'no-dupe-class-members': 'error',
	'no-dupe-else-if': 'error',
	'no-dupe-keys': 'error',
	'no-duplicate-case': 'error',
	'no-duplicate-imports': 'error',
	'no-empty-character-class': 'error',
	'no-empty-pattern': 'error',
	'no-ex-assign': 'error',
	'no-fallthrough': [ 'error', { allowEmptyCase: true } ],
	'no-func-assign': 'error',
	'no-import-assign': 'error',
	'no-inner-declarations': 'error',
	'no-invalid-regexp': 'error',
	'no-loss-of-precision': 'error',
	'no-misleading-character-class': 'error',
	'no-new-native-nonconstructor': 'error',
	'no-new-symbol': 'error',
	'no-obj-calls': 'error',
	'no-promise-executor-return': 'error',
	'no-prototype-builtins': 'error',
	'no-self-assign': 'error',
	'no-self-compare': 'error',
	'no-setter-return': 'error',
	'no-sparse-arrays': 'error',
	'no-template-curly-in-string': 'error',
	'no-this-before-super': 'error',
	'no-undef': 'error',
	'no-unexpected-multiline': 'error',
	'no-unmodified-loop-condition': 'error',
	'no-unreachable': 'error',
	'no-unreachable-loop': 'error',
	'no-unsafe-finally': 'error',
	'no-unsafe-negation': [ 'error', { enforceForOrderingRelations: true } ],
	'no-unsafe-optional-chaining': 'error',
	'no-unused-private-class-members': 'error',
	'no-unused-vars': [ 'error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' } ],
	'no-use-before-define': [ 'error', {
		functions: false,
		classes: true,
		variables: false,
		allowNamedExports: true,
	} ],
	'no-useless-backreference': 'error',
	'require-atomic-updates': [ 'error', {
		allowProperties: true,
	} ],
	'use-isnan': 'error',
	'valid-typeof': [ 'error', { requireStringLiterals: true } ],

	// Suggestions
	// These rules suggest alternate ways of doing things:
	'accessor-pairs': 'error',
	'arrow-body-style': [ 'error', 'as-needed' ],
	'block-scoped-var': 'error',
	camelcase: [ 'error', {
		properties: 'never',
	} ],
	'capitalized-comments': 'off',
	'class-methods-use-this': 'off',
	complexity: 'off',
	'consistent-return': 'error',
	'consistent-this': 'off',
	curly: 'error',
	'default-case': 'off',
	'default-case-last': 'error',
	'default-param-last': 'error',
	'dot-notation': 'off',
	eqeqeq: [ 'error', 'smart' ],
	'func-name-matching': 'error',
	'func-names': [ 'error', 'never' ],
	'func-style': [ 'error', 'declaration', { allowArrowFunctions: true } ],
	'grouped-accessor-pairs': [ 'error', 'getBeforeSet' ],
	'guard-for-in': 'error',
	'id-denylist': 'off',
	'id-length': 'off',
	'id-match': 'off',
	'init-declarations': 'off',
	'logical-assignment-operators': 'off',
	'max-classes-per-file': 'off',
	'max-depth': [ 'error', 4 ],
	'max-lines': [ 'error', { max: 500, skipBlankLines: true, skipComments: true } ],
	'max-lines-per-function': 'off',
	'max-nested-callbacks': [ 'error', 3 ],
	'max-params': [ 'error', 5 ],
	'max-statements': 'off',
	'new-cap': 'off',
	'no-alert': 'error',
	'no-array-constructor': 'error',
	'no-bitwise': 'error',
	'no-caller': 'error',
	'no-case-declarations': 'error',
	'no-console': [ 'warn', { allow: [ 'warn', 'error' ] } ],
	'no-continue': 'error',
	'no-delete-var': 'error',
	'no-div-regex': 'error',
	'no-else-return': 'error',
	'no-empty': 'error',
	'no-empty-function': 'error',
	'no-empty-static-block': 'error',
	'no-eq-null': 'off',
	'no-eval': 'error',
	'no-extend-native': 'error',
	'no-extra-bind': 'error',
	'no-extra-boolean-cast': 'error',
	'no-extra-label': 'error',
	'no-global-assign': 'error',
	'no-implicit-coercion': 'error',
	'no-implicit-globals': 'off',
	'no-implied-eval': 'error',
	'no-inline-comments': 'off',
	'no-invalid-this': 'error',
	'no-irregular-whitespace': 'error',
	'no-iterator': 'error',
	'no-label-var': 'error',
	'no-labels': 'off',
	'no-lone-blocks': 'error',
	'no-lonely-if': 'error',
	'no-loop-func': 'error',
	'no-magic-numbers': 'off',
	'no-multi-assign': 'error',
	'no-multi-str': 'error',
	'no-negated-condition': 'off',
	'no-nested-ternary': 'off',
	'no-new': 'error',
	'no-new-func': 'error',
	'no-new-wrappers': 'error',
	'no-nonoctal-decimal-escape': 'error',
	'no-object-constructor': 'error',
	'no-octal': 'error',
	'no-octal-escape': 'error',
	'no-param-reassign': 'error',
	'no-plusplus': 'off',
	'no-proto': 'error',
	'no-redeclare': 'error',
	'no-regex-spaces': 'off',
	'no-restricted-exports': 'off',
	'no-restricted-globals': 'off',
	'no-restricted-imports': 'off',
	'no-restricted-properties': 'off',
	'no-restricted-syntax': 'off',
	'no-return-assign': [ 'error', 'always' ],
	'no-script-url': 'error',
	'no-sequences': 'error',
	'no-shadow': [ 'error', { ignoreOnInitialization: true } ],
	'no-shadow-restricted-names': 'error',
	'no-ternary': 'off',
	'no-throw-literal': 'error',
	'no-undef-init': 'error',
	'no-undefined': 'off',
	'no-underscore-dangle': 'off',
	'no-unneeded-ternary': 'error',
	'no-unused-expressions': 'error',
	'no-unused-labels': 'error',
	// wait for eslint 9
	// "no-useless-assignment": "error",
	'no-useless-call': 'error',
	'no-useless-catch': 'error',
	'no-useless-computed-key': 'error',
	'no-useless-concat': 'error',
	'no-useless-constructor': 'error',
	'no-useless-escape': 'error',
	'no-useless-rename': 'error',
	'no-useless-return': 'error',
	'no-var': 'error',
	'no-void': [ 'error', {
		allowAsStatement: true,
	} ],
	'no-warning-comments': 'off',
	'no-with': 'error',
	'object-shorthand': [ 'error', 'always' ],
	'one-var': [ 'error', 'never' ],
	'operator-assignment': 'off',
	'prefer-arrow-callback': 'error',
	'prefer-const': 'error',
	'prefer-destructuring': 'off',
	'prefer-exponentiation-operator': 'error',
	'prefer-named-capture-group': 'off',
	'prefer-numeric-literals': 'error',
	'prefer-object-has-own': 'error',
	'prefer-object-spread': 'error',
	'prefer-promise-reject-errors': 'off',
	'prefer-regex-literals': 'error',
	'prefer-rest-params': 'error',
	'prefer-spread': 'error',
	'prefer-template': 'error',
	radix: 'off',
	'require-await': 'error',
	'require-unicode-regexp': 'off',
	'require-yield': 'error',
	'sort-imports': 'off',
	'sort-keys': 'off',
	'sort-vars': 'off',
	strict: [ 'error', 'never' ],
	'symbol-description': 'off',
	'vars-on-top': 'off',
	yoda: [ 'error', 'never' ],

	// Layout & Formatting
	// These rules care about how the code looks rather than how it executes:
	'line-comment-position': 'off',
	'unicode-bom': [ 'error', 'never' ],
};
