export default {
	// Base Rules (Enabling Correct ESLint Parsing)
	// Rules in this category are enabled for all presets provided by eslint-plugin-vue.
	'vue/comment-directive': 'error',
	'vue/jsx-uses-vars': 'error',

	// Priority A: Essential (Error Prevention)
	'vue/multi-word-component-names': 'off',
	'vue/no-arrow-functions-in-watch': 'error',
	'vue/no-async-in-computed-properties': 'error',
	'vue/no-child-content': 'error',
	'vue/no-computed-properties-in-data': 'error',
	'vue/no-deprecated-data-object-declaration': 'error',
	'vue/no-deprecated-destroyed-lifecycle': 'error',
	'vue/no-deprecated-dollar-listeners-api': 'error',
	'vue/no-deprecated-dollar-scopedslots-api': 'error',
	'vue/no-deprecated-events-api': 'error',
	'vue/no-deprecated-filter': 'error',
	'vue/no-deprecated-functional-template': 'error',
	'vue/no-deprecated-html-element-is': 'error',
	'vue/no-deprecated-inline-template': 'error',
	'vue/no-deprecated-props-default-this': 'error',
	'vue/no-deprecated-router-link-tag-prop': 'error',
	'vue/no-deprecated-scope-attribute': 'error',
	'vue/no-deprecated-slot-attribute': 'error',
	'vue/no-deprecated-slot-scope-attribute': 'error',
	'vue/no-deprecated-v-bind-sync': 'error',
	'vue/no-deprecated-v-is': 'error',
	'vue/no-deprecated-v-on-native-modifier': 'error',
	'vue/no-deprecated-v-on-number-modifiers': 'error',
	'vue/no-deprecated-vue-config-keycodes': 'error',
	'vue/no-dupe-keys': 'error',
	'vue/no-dupe-v-else-if': 'error',
	'vue/no-duplicate-attributes': 'error',
	'vue/no-export-in-script-setup': 'error',
	'vue/no-expose-after-await': 'error',
	'vue/no-lifecycle-after-await': 'error',
	'vue/no-mutating-props': 'error',
	'vue/no-parsing-error': 'error',
	'vue/no-ref-as-operand': 'error',
	'vue/no-reserved-component-names': 'error',
	'vue/no-reserved-keys': 'error',
	'vue/no-reserved-props': 'error',
	'vue/no-shared-component-data': 'error',
	'vue/no-side-effects-in-computed-properties': 'error',
	'vue/no-template-key': 'error',
	'vue/no-textarea-mustache': 'error',
	'vue/no-unused-components': 'error',
	'vue/no-unused-vars': 'error',
	'vue/no-use-computed-property-like-method': 'error',
	'vue/no-use-v-if-with-v-for': 'error',
	'vue/no-useless-template-attributes': 'error',
	'vue/no-v-for-template-key-on-child': 'error',
	'vue/no-v-text-v-html-on-component': 'error',
	'vue/no-watch-after-await': 'error',
	'vue/prefer-import-from-vue': 'off',
	'vue/require-component-is': 'error',
	'vue/require-prop-type-constructor': 'error',
	'vue/require-render-return': 'error',
	'vue/require-slots-as-functions': 'error',
	'vue/require-toggle-inside-transition': 'error',
	'vue/require-v-for-key': 'error',
	'vue/require-valid-default-prop': 'error',
	'vue/return-in-computed-property': 'error',
	'vue/return-in-emits-validator': 'error',
	'vue/use-v-on-exact': 'error',
	'vue/valid-attribute-name': 'error',
	'vue/valid-define-emits': 'error',
	'vue/valid-define-props': 'error',
	'vue/valid-next-tick': 'error',
	'vue/valid-template-root': 'error',
	'vue/valid-v-bind': 'error',
	'vue/valid-v-cloak': 'error',
	'vue/valid-v-else-if': 'error',
	'vue/valid-v-else': 'error',
	'vue/valid-v-for': 'error',
	'vue/valid-v-html': 'error',
	'vue/valid-v-if': 'error',
	'vue/valid-v-is': 'error',
	'vue/valid-v-memo': 'error',
	'vue/valid-v-model': 'error',
	'vue/valid-v-on': 'error',
	'vue/valid-v-once': 'error',
	'vue/valid-v-pre': 'error',
	'vue/valid-v-show': 'error',
	'vue/valid-v-slot': 'error',
	'vue/valid-v-text': 'error',

	// Priority B: Strongly Recommended (Improving Readability)
	'vue/attribute-hyphenation': 'error',
	'vue/component-definition-name-casing': 'error',
	'vue/first-attribute-linebreak': [ 'error', {
		singleline: 'beside',
		multiline: 'below',
	} ],
	'vue/html-closing-bracket-newline': 'error',
	'vue/html-closing-bracket-spacing': 'error',
	'vue/html-end-tags': 'error',
	'vue/html-indent': [ 'error', 'tab' ],
	'vue/html-quotes': [ 'error', 'double', { avoidEscape: true } ],
	'vue/html-self-closing': 'error',
	'vue/max-attributes-per-line': 'error',
	'vue/multiline-html-element-content-newline': 'error',
	'vue/mustache-interpolation-spacing': 'error',
	'vue/no-multi-spaces': 'error',
	'vue/no-spaces-around-equal-signs-in-attribute': 'error',
	'vue/no-template-shadow': 'error',
	'vue/one-component-per-file': 'error',
	'vue/prop-name-casing': 'error',
	'vue/require-default-prop': 'error',
	'vue/require-explicit-emits': 'error',
	'vue/require-prop-types': 'error',
	'vue/singleline-html-element-content-newline': 'error',
	'vue/v-bind-style': 'error',
	'vue/v-on-event-hyphenation': 'error',
	'vue/v-on-style': 'error',
	'vue/v-slot-style': 'error',

	// Priority C: Recommended (Potentially Dangerous Patterns)
	'vue/attributes-order': 'error',
	'vue/no-lone-template': 'error',
	'vue/no-multiple-slot-args': 'error',
	'vue/no-v-html': 'off',
	'vue/order-in-components': 'error',
	'vue/this-in-template': 'error',

	// Uncategorized
	// Possible problems
	// These rules relate to possible logic errors in code.
	'vue/match-component-import-name': 'error',
	'vue/max-lines-per-block': 'error',
	'vue/no-deprecated-model-definition': 'error',
	'vue/no-ref-object-reactivity-loss': 'error',
	'vue/no-required-prop-with-default': 'error',
	'vue/no-restricted-class': 'off',
	'vue/no-template-target-blank': 'off',
	'vue/no-this-in-before-route-enter': 'error',
	'vue/prefer-prop-type-boolean-first': 'error',
	'vue/require-explicit-slots': 'off',
	'vue/v-if-else-key': 'off',
	'vue/valid-define-options': 'error',
	// Suggestions
	// These rules suggest alternate ways of doing things.
	'vue/block-lang': [ 'error',
		{
			script: {
				lang: 'ts',
			},
			style: {
				allowNoLang: true,
			},
		} ],
	'vue/block-order': [ 'error', { order: [ 'template', 'script', 'style', 'docs' ] } ],
	'vue/component-api-style': 'error',
	'vue/component-name-in-template-casing': [ 'error', 'PascalCase', {
		registeredComponentsOnly: false,
		ignores: [],
	} ],
	'vue/component-options-name-casing': 'error',
	'vue/custom-event-name-casing': 'error',
	'vue/define-emits-declaration': [ 'error', 'type-literal' ],
	'vue/define-props-declaration': 'error',
	'vue/enforce-style-attribute': [ 'error', { allow: [ 'scoped' ] } ],
	'vue/html-button-has-type': 'error',
	'vue/match-component-file-name': 'error',
	'vue/next-tick-style': 'error',
	'vue/no-bare-strings-in-template': 'off',
	'vue/no-boolean-default': 'error',
	'vue/no-duplicate-attr-inheritance': 'error',
	'vue/no-empty-component-block': 'error',
	'vue/no-multiple-objects-in-class': 'error',
	'vue/no-potential-component-option-typo': 'error',
	'vue/no-restricted-block': 'off',
	'vue/no-restricted-call-after-await': 'error',
	'vue/no-restricted-component-names': 'off',
	'vue/no-restricted-component-options': 'off',
	'vue/no-restricted-custom-event': 'off',
	'vue/no-restricted-html-elements': 'off',
	'vue/no-restricted-props': 'off',
	'vue/no-restricted-static-attribute': 'off',
	'vue/no-restricted-v-bind': 'off',
	'vue/no-restricted-v-on': 'off',
	'vue/no-root-v-if': 'error',
	'vue/no-setup-props-reactivity-loss': 'error',
	'vue/no-static-inline-styles': [ 'error', {
		allowBinding: true,
	} ],
	'vue/no-undef-components': 'off',
	'vue/no-undef-properties': 'off',
	'vue/no-unsupported-features': 'off',
	'vue/no-unused-emit-declarations': 'error',
	'vue/no-unused-properties': 'off',
	'vue/no-unused-refs': 'error',
	'vue/no-use-v-else-with-v-for': 'error',
	'vue/no-useless-mustaches': [ 'error', {
		ignoreStringEscape: true,
	} ],
	'vue/no-useless-v-bind': [ 'error', {
		ignoreStringEscape: true,
	} ],
	'vue/no-v-text': 'error',
	'vue/prefer-define-options': 'error',
	'vue/prefer-separate-static-class': 'error',
	'vue/prefer-true-attribute-shorthand': 'error',
	'vue/require-direct-export': 'off',
	'vue/require-emit-validator': 'error',
	'vue/require-expose': 'off',
	'vue/require-macro-variable-name': 'error',
	'vue/require-name-property': 'off',
	'vue/require-prop-comment': 'off',
	'vue/require-typed-object-prop': 'error',
	'vue/require-typed-ref': 'error',
	'vue/sort-keys': 'off',
	'vue/static-class-names-order': 'off',
	'vue/v-on-handler-style': 'off', // wait for https://github.com/vuejs/eslint-plugin-vue/issues/2460
	// Layout & formatting
	// These rules care about how the code looks rather than how it executes.
	'vue/block-tag-newline': [ 'error', {
		singleline: 'always',
		multiline: 'always',
	} ],
	'vue/define-macros-order': [ 'error', {
		order: [ 'defineOptions', 'defineModel', 'defineProps', 'defineEmits', 'defineSlots' ],
		defineExposeLast: true,
	} ],
	'vue/html-comment-content-newline': 'off',
	'vue/html-comment-content-spacing': 'off',
	'vue/html-comment-indent': 'off',
	'vue/new-line-between-multi-line-property': 'error',
	'vue/padding-line-between-blocks': 'error',
	'vue/padding-line-between-tags': 'off',
	'vue/padding-lines-in-component-definition': 'error',
	'@stylistic/indent': 'off',
	'vue/script-indent': [ 'error', 'tab' ],
	'vue/v-for-delimiter-style': 'error',

	// Extension rules
	// Possible problems
	// These rules relate to possible logic errors in code.
	'vue/no-constant-condition': 'error',
	'vue/no-empty-pattern': 'error',
	'vue/no-irregular-whitespace': 'error',
	'vue/no-loss-of-precision': 'error',
	'vue/no-sparse-arrays': 'error',
	// Suggestions
	// These rules suggest alternate ways of doing things.
	camelcase: [ 'error', {
		properties: 'never',
	} ],
	'vue/dot-notation': 'off',
	'vue/eqeqeq': [ 'error', 'smart' ],
	'vue/no-console': [ 'warn', { allow: [ 'warn', 'error' ] } ],
	'vue/no-restricted-syntax': 'off',
	'vue/no-useless-concat': 'error',
	'vue/object-shorthand': [ 'error', 'always' ],
	'vue/prefer-template': 'error',
	// Layout & formatting
	// These rules care about how the code looks rather than how it executes.
	'vue/array-bracket-newline': [ 'error', 'consistent' ],
	'vue/array-bracket-spacing': [ 'error', 'always' ],
	'vue/array-element-newline': [ 'error', 'consistent' ],
	'vue/arrow-spacing': [ 'error', { after: true, before: true } ],
	'vue/block-spacing': [ 'error', 'always' ],
	'vue/brace-style': [ 'error', 'stroustrup', { allowSingleLine: true } ],
	'vue/comma-dangle': [ 'error', 'always-multiline' ],
	'vue/comma-spacing': [ 'error', { after: true, before: false } ],
	'vue/comma-style': [ 'error', 'last' ],
	'vue/dot-location': [ 'error', 'property' ],
	'vue/func-call-spacing': [ 'error', 'never' ],
	'vue/key-spacing': [ 'error', { afterColon: true, beforeColon: false } ],
	'vue/keyword-spacing': [ 'error', { after: true, before: true } ],
	'vue/max-len': 'off',
	'vue/multiline-ternary': 'off',
	'vue/no-extra-parens': 'off',
	'vue/object-curly-newline': [ 'error', { consistent: true } ],
	'vue/object-curly-spacing': [ 'error', 'always' ],
	'vue/object-property-newline': [ 'error', { allowAllPropertiesOnSameLine: false } ],
	'vue/operator-linebreak': 'error',
	'vue/quote-props': [ 'error', 'as-needed' ],
	'vue/space-in-parens': [ 'error', 'never' ],
	'vue/space-infix-ops': 'error',
	'vue/space-unary-ops': [ 'error', { nonwords: false, words: true } ],
	'vue/template-curly-spacing': [ 'error', 'always' ],
};
